# permissions for end users to edit buildkites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cops-buildkit
    app.kubernetes.io/managed-by: kustomize
  name: buildkite-editor-role
rules:
- apiGroups:
  - buildkit.thecops.dev
  resources:
  - buildkites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - buildkit.thecops.dev
  resources:
  - buildkites/status
  verbs:
  - get
