apiVersion: cops-buildkit.thecops.dev/v1alpha1
kind: Buildkit
metadata:
  labels:
    app.kubernetes.io/name: cops-buildkit
    app.kubernetes.io/managed-by: kustomize
  name: buildkit-sample
spec:
  # TODO(user): Add fields here
